const localizedTextsMap = {
  noRowsLabel: 'No hay filas',
  noResultsOverlayLabel: 'No se encontraron resultados',
  toolbarDensity: 'Densidad',
  toolbarDensityLabel: 'Densidad',
  toolbarDensityCompact: 'Compacta',
  toolbarDensityStandard: 'Estándar',
  toolbarDensityComfortable: 'Cómoda',
  toolbarColumns: 'Columnas',
  toolbarColumnsLabel: 'Columnas',
  toolbarFilters: 'Filtros',
  toolbarFiltersLabel: 'Filtros',
  toolbarFiltersTooltipHide: 'Ocultar filtros',
  toolbarFiltersTooltipShow: 'Mostrar filtros',
  toolbarFiltersTooltipActive: (count: number) =>
    `${count} filtro${count !== 1 ? 's' : ''} activo${count !== 1 ? 's' : ''}`,
  toolbarQuickFilterPlaceholder: 'Buscar...',
  toolbarQuickFilterLabel: 'Filtro rápido',
  toolbarQuickFilterDeleteIconLabel: 'Borrar filtro rápido',
  toolbarExport: 'Exportar',
  toolbarExportLabel: 'Exportar',
  toolbarExportCSV: 'Descargar como CSV',
  toolbarExportPrint: 'Imprimir',
  toolbarExportExcel: 'Descargar como Excel',
  columnsManagementSearchTitle: 'Buscar columnas',
  columnsManagementNoColumns: 'No hay columnas',
  columnsManagementShowHideAllText: 'Mostrar/Ocultar todo',
  columnsManagementReset: 'Restablecer',
  columnsManagementDeleteIconLabel: 'Eliminar',
  filterPanelAddFilter: 'Agregar filtro',
  filterPanelRemoveAll: 'Eliminar todos',
  filterPanelDeleteIconLabel: 'Eliminar',
  filterPanelLogicOperator: 'Operador lógico',
  filterPanelOperator: 'Operador',
  filterPanelOperatorAnd: 'Y',
  filterPanelOperatorOr: 'O',
  filterPanelColumns: 'Columnas',
  filterPanelInputLabel: 'Valor',
  filterPanelInputPlaceholder: 'Escribe un valor',
  filterOperatorContains: 'Contiene',
  filterOperatorDoesNotContain: 'No contiene',
  filterOperatorEquals: 'Es igual a',
  filterOperatorDoesNotEqual: 'No es igual a',
  filterOperatorStartsWith: 'Comienza con',
  filterOperatorEndsWith: 'Termina con',
  filterOperatorIs: 'Es',
  filterOperatorNot: 'No es',
  filterOperatorAfter: 'Después de',
  filterOperatorOnOrAfter: 'En o después de',
  filterOperatorBefore: 'Antes de',
  filterOperatorOnOrBefore: 'En o antes de',
  filterOperatorIsEmpty: 'Está vacío',
  filterOperatorIsNotEmpty: 'No está vacío',
  filterOperatorIsAnyOf: 'Es cualquiera de',
  'filterOperator=': 'Es igual a',
  'filterOperator!=': 'No es igual a',
  'filterOperator>': 'Mayor que',
  'filterOperator>=': 'Mayor o igual que',
  'filterOperator<': 'Menor que',
  'filterOperator<=': 'Menor o igual que',
  headerFilterOperatorContains: 'Contiene',
  headerFilterOperatorDoesNotContain: 'No contiene',
  headerFilterOperatorEquals: 'Es igual a',
  headerFilterOperatorDoesNotEqual: 'No es igual a',
  headerFilterOperatorStartsWith: 'Comienza con',
  headerFilterOperatorEndsWith: 'Termina con',
  headerFilterOperatorIs: 'Es',
  headerFilterOperatorNot: 'No es',
  headerFilterOperatorAfter: 'Después de',
  headerFilterOperatorOnOrAfter: 'En o después de',
  headerFilterOperatorBefore: 'Antes de',
  headerFilterOperatorOnOrBefore: 'En o antes de',
  headerFilterOperatorIsEmpty: 'Está vacío',
  headerFilterOperatorIsNotEmpty: 'No está vacío',
  headerFilterOperatorIsAnyOf: 'Es cualquiera de',
  'headerFilterOperator=': 'Es igual a',
  'headerFilterOperator!=': 'No es igual a',
  'headerFilterOperator>': 'Mayor que',
  'headerFilterOperator>=': 'Mayor o igual que',
  'headerFilterOperator<': 'Menor que',
  'headerFilterOperator<=': 'Menor o igual que',
  filterValueAny: 'Cualquiera',
  filterValueTrue: 'Verdadero',
  filterValueFalse: 'Falso',
  columnMenuLabel: 'Menú',
  columnMenuShowColumns: 'Mostrar columnas',
  columnMenuManageColumns: 'Gestionar columnas',
  columnMenuFilter: 'Filtrar',
  columnMenuHideColumn: 'Ocultar columna',
  columnMenuUnsort: 'Quitar orden',
  columnMenuSortAsc: 'Ordenar ascendente',
  columnMenuSortDesc: 'Ordenar descendente',
  columnHeaderFiltersTooltipActive: (count: number) =>
    `${count} filtro${count !== 1 ? 's' : ''} activo${count !== 1 ? 's' : ''}`,
  columnHeaderFiltersLabel: 'Filtros',
  columnHeaderSortIconLabel: 'Ordenar',
  footerRowSelected: (count: number) =>
    `${count} fila${count !== 1 ? 's' : ''} seleccionada${count !== 1 ? 's' : ''}`,
  footerTotalRows: 'Total de filas:',
  footerTotalVisibleRows: (visibleCount: number, totalCount: number) =>
    `${visibleCount} de ${totalCount}`,
  checkboxSelectionHeaderName: 'Selección',
  checkboxSelectionSelectAllRows: 'Seleccionar todas las filas',
  checkboxSelectionUnselectAllRows: 'Deseleccionar todas las filas',
  checkboxSelectionSelectRow: 'Seleccionar fila',
  checkboxSelectionUnselectRow: 'Deseleccionar fila',
  booleanCellTrueLabel: 'Sí',
  booleanCellFalseLabel: 'No',
  actionsCellMore: 'Más',
  pinToLeft: 'Fijar a la izquierda',
  pinToRight: 'Fijar a la derecha',
  unpin: 'Desfijar',
  treeDataGroupingHeaderName: 'Agrupación',
  treeDataExpand: 'Expandir',
  treeDataCollapse: 'Colapsar',
  groupingColumnHeaderName: 'Agrupación',
  groupColumn: (name: string) => `Agrupar por ${name}`,
  unGroupColumn: (name: string) => `Desagrupar por ${name}`,
  detailPanelToggle: 'Alternar panel de detalles',
  expandDetailPanel: 'Expandir detalles',
  collapseDetailPanel: 'Colapsar detalles',
  rowReorderingHeaderName: 'Reordenar filas',
  aggregationMenuItemHeader: 'Agregación',
  aggregationFunctionLabelSum: 'Suma',
  aggregationFunctionLabelAvg: 'Promedio',
  aggregationFunctionLabelMin: 'Mínimo',
  aggregationFunctionLabelMax: 'Máximo',
  aggregationFunctionLabelSize: 'Tamaño',
  MuiTablePagination: {
    labelRowsPerPage: 'Filas por página:',
    labelDisplayedRows: ({ from, to, count }) =>
      `${from}–${to} de ${count !== -1 ? count : `más de ${to}`}`,
  },
};

export default localizedTextsMap;
