import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { theme } from '@/styles/Theme';
import ClientQueryProvider from '@/context/ClientQueryProvider/ClientQueryProvider';
import { GlobalModalProvider } from '@/context/GlobalModalContext/GlobalModalContext';
import ClientLayout from './(clientlayout)/ClientLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`roboto.variable`}>
        <ClientQueryProvider>
          <InitColorSchemeScript attribute='class' />
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <GlobalModalProvider>
                <CssBaseline />
                <ClientLayout>{children}</ClientLayout>
              </GlobalModalProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ClientQueryProvider>
      </body>
    </html>
  );
}
